### ISSUE TITLE
Websocket Issue

### ISSUE THREAD

**Issue by tech-geek-4** [machgo/fellerwiserhomeassistant#19]
Good day, since updating HA to 2025.6.1 ghe integration isn't working properly anymore. 
I can for example move covers by slider or buthen but ghe state doesn't get updated nor the position (moving, open, closed) or the percent value. 

I get the following error in HA when reloadingvthe integration:
```

Dieser Fehler stammt von einer benutzerdefinierten Integration

Logger: homeassistant
Quelle: custom_components/fellerwiser/cover.py:33
Integration: Feller Wiser (Dokumentation, Probleme)
Erstmals aufgetreten: 12:39:57 (4 Vorkommnisse)
Zuletzt protokolliert: 13:07:07

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/fellerwiser/cover.py", line 33, in hello
    async with websockets.connect("ws://"+ip+"/api", additional_headers={'authorization':'Bearer ' + apikey}, ping_timeout=None) as ws:
               ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/websockets/legacy/client.py", line 635, in __aenter__
    return await self
           ^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/websockets/legacy/client.py", line 654, in __await_impl__
    _transport, protocol = await self._create_connection()
                                 ~~~~~~~~~~~~~~~~~~~~~~~^^
TypeError: BaseEventLoop.create_connection() got an unexpected keyword argument 'additional_headers'

```

Does anyone have an idea what the problem could be?
Rebooting of both HA and Wiser didn't helped...🤷🏻‍♂️

Thanks for quick inputs before i have to move back to an old version...🤪

**Comment by tech-geek-4** [comment]
Same in lights.py

```

Dieser Fehler stammt von einer benutzerdefinierten Integration

Logger: homeassistant
Quelle: custom_components/fellerwiser/light.py:33
Integration: Feller Wiser (Dokumentation, Probleme)
Erstmals aufgetreten: 12:39:58 (4 Vorkommnisse)
Zuletzt protokolliert: 13:07:07

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/fellerwiser/light.py", line 33, in hello
    async with websockets.connect("ws://"+ip+"/api", additional_headers={'authorization':'Bearer ' + apikey}, ping_timeout=None) as ws:
               ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/websockets/legacy/client.py", line 635, in __aenter__
    return await self
           ^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/websockets/legacy/client.py", line 654, in __await_impl__
    _transport, protocol = await self._create_connection()
                                 ~~~~~~~~~~~~~~~~~~~~~~~^^
TypeError: BaseEventLoop.create_connection() got an unexpected keyword argument 'additional_headers'

```

**Comment by tech-geek-4** [comment]
Could fix the issue with the following tip from @kess78! Thanks!

https://github.com/machgo/fellerwiserhomeassistant/issues/15#issuecomment-2660909790

But seems weird as it worked with my previous instance 2025.4.x without an issue and stopped now with 2025.6.1 without any change in any configuration. 

Maybe we can investigate this a little more as it seems i'm not the only one with this issue...

Regards

**Comment by ReTo007** [comment]
Hi there,
Same issue here. I confirm that the integration stopped working with the error as described above when upgrading to 2025.6.0 and persists after upgrading to 2025.6.1.
I'm operating two HomeAssistant systems. One is running in a docker container and the other one is running HomeAssistant OS. The issue occurred on both systems when upgrading to 2025.6.0.
I confirm as well the fix mentioned above by tech-geek-4 worked for me for now. Let's see for how long...
Any input on coming to a future proof fix would be kindly appreciated.
Cheers, Reto
